# Generated by Django 4.1.1 on 2022-10-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ML_algorithms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('algo_type', models.CharField(choices=[('Supervised', 'SL'), ('Unsupervised', 'UL'), ('Reinforcement', 'RL')], max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ML_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_file', models.FileField(blank=True, null=True, upload_to='user_created_models')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ml_algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ML_models.ml_algorithms')),
            ],
        ),
    ]
