# Generated by Django 4.1.1 on 2022-10-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML_models', '0002_alter_ml_algorithms_algo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_algorithms',
            name='algo_type',
            field=models.CharField(choices=[('SL', 'Supervised'), ('UL', 'Unsupervised'), ('RL', 'Reinforcement')], max_length=2),
        ),
    ]
