# Generated by Django 4.1.1 on 2022-10-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML_models', '0003_alter_ml_algorithms_algo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='models_data'),
        ),
    ]
