# Generated by Django 4.1.1 on 2022-10-23 20:21

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('ML_models', '0004_ml_model_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='target',
            field=models.CharField(default=sqlalchemy.sql.expression.null, max_length=200),
        ),
    ]
