# Generated by Django 4.1.1 on 2022-10-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML_models', '0005_ml_model_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ml_model',
            name='title',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
