# Generated by Django 4.1.1 on 2022-10-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML_models', '0006_ml_model_description_ml_model_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
