# Generated by Django 4.1.1 on 2022-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML_models', '0008_alter_ml_model_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='target',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
